### ISSUE TITLE
Create Assistant Styling

### ISSUE THREAD

**Issue by alchemypls** [jtcCapstone/bloomCapstone#17]
# 17 - Create Assistant Styling

**Milestone**: Guided Assistant Foundation (Week 1)

**Labels**: styling, ui-seeds, accessibility

**Description**:
Implement the styling for the Income Assistant to match the UI Seeds design system and ensure accessibility compliance.

**Technical Context**:
Building on the chat interface from #15 and state management from #16, we'll implement the visual design using UI Seeds components and SCSS modules.

**Dependencies**:
- #15 - Basic Chat Interface
- #16 - Assistant State Management

**Acceptance Criteria**:

1. Create SCSS Modules:
   ```scss
   // IncomeAssistant.module.scss
   @import "@bloom-housing/ui-seeds/src/styles/tokens.scss";

   .assistant {
     display: flex;
     flex-direction: column;
     height: 100%;
     background-color: $seed-color-background;
     border-radius: $seed-border-radius-lg;
     box-shadow: $seed-shadow-md;
   }

   .header {
     display: flex;
     justify-content: space-between;
     align-items: center;
     padding: $seed-spacing-md;
     border-bottom: 1px solid $seed-color-border;
   }

   .content {
     flex: 1;
     overflow-y: auto;
     padding: $seed-spacing-md;
   }

   .messageList {
     display: flex;
     flex-direction: column;
     gap: $seed-spacing-sm;
   }

   .message {
     max-width: 80%;
     padding: $seed-spacing-sm;
     border-radius: $seed-border-radius-md;
     
     &.user {
       align-self: flex-end;
       background-color: $seed-color-primary;
       color: $seed-color-white;
     }
     
     &.assistant {
       align-self: flex-start;
       background-color: $seed-color-background-alt;
     }
   }

   .inputContainer {
     padding: $seed-spacing-md;
     border-top: 1px solid $seed-color-border;
   }
   ```

2. Implement UI Seeds Components:
   ```typescript
   // IncomeAssistant.tsx
   import React from "react"
   import { t } from "@bloom-housing/ui-components"
   import { Card, Button, Icon } from "@bloom-housing/ui-seeds"
   import { IncomeAssistantProps } from "./IncomeAssistant.types"
   import styles from "./IncomeAssistant.module.scss"

   const IncomeAssistant = (props: IncomeAssistantProps) => {
     const { isOpen, onClose, className, id, testId, ariaLabel, ariaControls, children } = props

     return (
       <Card className={`${styles.assistant} ${className}`} id={id} data-testid={testId}>
         <div className={styles.header}>
           <h2>{t("assistant.title")}</h2>
           <Button
             variant="text"
             onClick={onClose}
             aria-label={t("assistant.close")}
           >
             <Icon symbol="close" size="sm" />
           </Button>
         </div>
         <div className={styles.content} role="log" aria-live="polite">
           {children}
         </div>
       </Card>
     )
   }

   export { IncomeAssistant as default, IncomeAssistant }
   ```

3. Add Responsive Design:
   ```scss
   // IncomeAssistant.module.scss
   @media (max-width: $seed-breakpoint-sm) {
     .assistant {
       border-radius: 0;
       height: 100vh;
     }

     .message {
       max-width: 90%;
     }
   }
   ```

4. Accessibility Styling:
   - Color contrast compliance
   - Focus states
   - Screen reader support
   - Proper ARIA attributes

**UI Resources**:
1. **Design System Documentation**:
   - [UI Seeds Storybook](https://storybook-ui-seeds.netlify.app/?path=/story/tokens-introduction--page)
   - [UI Seeds Design System (Zeroheight)](https://zeroheight.com/5e69dd4e1/p/938cb5-seeds-design-system)
   - [UI Seeds Repository](https://github.com/bloom-housing/ui-seeds)

2. **Legacy Components (Fallback)**:
   - [UI Components Storybook](https://storybook.bloom.exygy.dev/)
   - [UI Components Repository](https://github.com/bloom-housing/ui-components)

3. **Development Tools**:
   - [Prettier VSCode Extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
   - [CSS Variables Autocomplete](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables)
   - [CSS Modules Autocomplete](https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules)

4. **Accessibility Resources**:
   - [WCAG 2.1 Guidelines](https://www.w3.org/TR/WCAG21/)
   - [ARIA Practices](https://www.w3.org/WAI/ARIA/apg/)

**Technical Requirements**:
- Use UI Seeds design tokens
- Implement responsive breakpoints
- Follow WCAG 2.1 AA standards
- Use SCSS modules
- Include proper error states

**Definition of Done**:
- All acceptance criteria met
- Styles match UI Seeds design system
- Accessibility requirements verified
- Code reviewed and approved
- Documentation complete

**Resources**:
- UI Seeds Design System
- SCSS Documentation
- WCAG 2.1 Guidelines

**Notes**:
- Focus on mobile-first implementation
- Ensure smooth animations and transitions
- Consider performance implications
- Document style decisions
- Plan for future theme customization
